#!/bin/bash

dir="$(dirname "$(readlink -m "$0")")"
. "$dir/bash-functions"

usage() {
	blue "Usage:"
	cat <<-USAGE
		  $0 user/repo

		  Clones the GitHub repository at github.com/user/repo
		USAGE
	exit 1
}

if [[ $1 != */* ]]; then
	usage
fi

repo="$1"
shift

green Cloning https://github.com/"$repo"
git clone "git@github.com:$repo" "$@"
