#!/bin/bash

dir="$(dirname "$(readlink -m "$0")")"
. "$dir/bash-functions"

usage() {
	blue "Usage:"
	cat <<-USAGE
		  $0
		  $0 repo
		  $0 repo/branch
		Example:
		  $0
		  $0 origin
		  $0 origin/master
		USAGE
	exit 1
}

fixcolors() {
	sed 's/\x1B\[m/\x1B\[0m/'
}

fetch=1

while [[ "$1" == -* ]]; do
	case "$1" in
		--no-fetch)
			fetch=0
			;;
		*)
			usage
			;;
	esac
	shift
done

parse_source_args "$@"

clear

green Local status
git --no-pager -c color.ui=always status | fixcolors
(( "$?" != 0 )) && exit $?

green Stashes
git --no-pager -c color.ui=always stash list --oneline | fixcolors

if (( "$fetch" == 1 )); then
	green "Fetching $source..."
	git --no-pager fetch "$source"
fi

green "Incoming changes:"
"$dir/git-incoming" --no-pager '-c color.ui=always' "$branch" | fixcolors

green "Outgoing changes:"
"$dir/git-outgoing" --no-pager '-c color.ui=always' "$branch" | fixcolors

echo
