#!/bin/bash

dir="$(dirname "$(readlink -m "$0")")"
. "$dir/bash-functions"

num=20
if [[ $1 =~ ^[0-9]+$ ]]; then
	num="$1"
	shift
fi

red Showing last $num commits

git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' --all -n "$num" "$@"
