#!/bin/bash

dir="$(dirname "$(readlink -m "$0")")"
. "$dir/bash-functions"

limit=true
num=30
if [[ $1 =~ ^[0-9]+$ ]]; then
	num="$1"
	shift
elif [[ $1 == --base ]]; then
    limit=false
    base="$2"
    shift
    shift
fi

OPTIONS=()
if $limit; then
    red "Showing last $num commits"

    OPTIONS+=(-n "$num")
    for arg in "$@"; do
        OPTIONS+=("$arg")
    done
else
    red "Showing commits since $base"
    for arg in "$@"; do
        if [[ $arg =~ ^-.* ]]; then
            # Pass argument directly
            OPTIONS+=("$arg")
        else
            OPTIONS+=("$base^..$arg")
        fi
    done
fi

git log --graph --abbrev-commit --decorate --format=format:'%C(bold blue)%h%C(reset) - %C(bold green)(%ar)%C(reset) %C(white)%s%C(reset) %C(dim white)- %an%C(reset)%C(bold yellow)%d%C(reset)' "${OPTIONS[@]}"
